name: build images

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - main
    paths:
      - images/**

permissions:
  packages: write
  contents: read

jobs:
  build:
    name: "Build and push ${{ matrix.tag }}:latest"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - arkmanager
          - arkmanager-2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect changes in ${{ matrix.tag }}
        id: changes
        uses: dorny/paths-filter@v3
        with:
          list-files: json
          filters: |
            ${{ matrix.tag }}:
              - 'images/${{ matrix.tag }}/**'

      - name: Repository owner to lowercase
        if: ${{ steps.changes.outputs[matrix.tag] == 'true' }}
        id: lower-repo
        run: echo "repository=$(echo $GITHUB_REPOSITORY_OWNER | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Setup Docker Buildx
        if: ${{ steps.changes.outputs[matrix.tag] == 'true' }}
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        if: ${{ steps.changes.outputs[matrix.tag] == 'true' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        if: ${{ steps.changes.outputs[matrix.tag] == 'true' }}
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to GHCR and DockerHub
        if: ${{ steps.changes.outputs[matrix.tag] == 'true' }}
        uses: docker/build-push-action@v6
        with:
          context: ./images/${{ matrix.tag }}
          file: ./images/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64
          push: true
          provenance: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ghcr.io/${{ steps.lower-repo.outputs.repository }}/${{ matrix.tag }}:latest
            docker.io/${{ vars.DOCKERHUB_USERNAME }}/${{ matrix.tag }}:latest
